### ISSUE TITLE
Sonar Scan

### ISSUE THREAD

**Issue by Phong6698** [MastersProjects/staySmart#20]
![image](https://user-images.githubusercontent.com/13161221/68536819-5c13de00-0359-11ea-829f-ec6cb28dd21f.png)

**Comment by Phong6698** [comment]
https://github.com/travis-ci/travis-ci/issues/7182
https://travis-ci.community/t/deploy-fails-with-aws-signaturedoesnotmatch/5835

I created Sonar Token from my account and used it:
```
addons:
  sonarcloud:
    organization: "mastersprojects" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
```

but now the error is "You're not authorized to run analysis. Please contact the project administrator."
![image](https://user-images.githubusercontent.com/13161221/68536851-e9573280-0359-11ea-8856-bcd75515932c.png)

gonna disable sonar-scan till it's fixed
